version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: America/Cancun
  open-pull-requests-limit: 99
  reviewers:
  - bbarker
  ignore:
  - dependency-name: react-devtools
    versions:
    - 4.12.2
  - dependency-name: purescript
    versions:
    - 0.14.0
  - dependency-name: google-closure-compiler
    versions:
    - 20210106.0.0
    - 20210202.0.0
    - 20210302.0.0
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
