#!/usr/bin/env sh

# Like prod, but doesn't minify

GCC=$(npm bin)/google-closure-compiler

preGccBuildSteps () {
  rimraf prod dist && mkdir prod && ln -sfn ../css prod/css && \
    spago build && spago bundle-module --main Metajelo.UI --to prod/index.prod.js && \
    cp static/index.* prod/
}

preGccBuildSteps || { echo 'preGccBuildSteps failed' ; exit 1; }
cp prod/index.prod.js prod/index.opt.js && \
# "$GCC" --js prod/index.prod.js --js_output_file prod/index.opt.js && \
  parcel build --public-url ./ prod/index.html --no-minify
#  parcel build --public-url ./ prod/index.html

