# TODO: Dhall: https://gvolpe.github.io/blog/github-actions-nix-cachix-dhall/

name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/0b8799ecaaf0dc6b4c11583a3c96ca5b40fcfdfb.tar.gz # in 20.09, Oct 9 2020
    - run: nix-shell -p spago nodejs purescript --command 'npm install && npm run build && npm run prod'
