name: "Deploy"
on:
  push:
    branches:
      - master
jobs:
  buildDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          # nix_path: nixpkgs=channel:nixos-20.09
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/0b8799ecaaf0dc6b4c11583a3c96ca5b40fcfdfb.tar.gz # in 20.09, Oct 9 2020
      - name: Build 👷
        run: nix-shell -p spago nodejs purescript --command './scripts/dist_build_commands.sh'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
